#define ISBIT(x,pos)	( ( (x) & ( 0x1 << (pos) ) ) != 0 )
#define GETBIT(x,pos)	( (x) & ( 0x1 << (pos) ) )
#define GETBITS(x,y,pos)	( (x) & ( y << (pos) ) )
#define SETBIT(x,pos)	( (x) |= ( 0x1 << (pos) ) )
#define UNSETBIT(x,pos)	( (x) &= (~( 0x1 << (pos) ) ) )
#define SETBITS(x,y,pos)	( (x) |= ( y << (pos) ) )
#define UNSETBITS(x,y,pos)	( (x) &= (~( y << (pos) ) ) )
